AUDIT_ERROR = "ERR"
AUDIT_TRUE = "No Vul"
AUDIT_FALSE = "Vul Found"
AUDIT_UNKNOWN = "UNKNOWN"

AUDIT_STEP_CHANGED = "(Changed)"
AUDIT_STEP_INIT = "Initial audit"
AUDIT_STEP_INSTALL = "After package-lock install"
AUDIT_STEP_FIX = "After audit fix"
AUDIT_STEP_FORCE_FIX = "After audit fix --force"
AUDIT_STEP_FAIL = "Fail"

DDP_CHECKER_UNMET_DEPENDENCY = "UNMET DEPENDENCY"
DDP_CHECKER_EMPTY = "EMPTY"

TEST_TRUE = "PASSED"
TEST_FALSE = "FAILED"
